#include "languages.h"

#include <string.h>

int lng_IndexFromString( const char* str)
{
    int index = 0;

    while( strcmp( str, english_lng[index]) != 0 && index < LNG_MAXENTRIES) index++;

    return index;
}

const char* const english_lng[] = {
    "PLAY GAME",
    "HI-SCORES",
    "GAME OPTIONS",
    "SOUND OPTIONS",
    "EXIT",
    "1 PLAYER",
    "GAME",
    "2 PLAYER",
    "CO-OP",
    "2 PLAYER",
    "VERSUS",
    "CONTINUE",
    "CHANGE TILESET",
    "CHANGE LAYOUT",
    "HOVER HINT ON/OFF",
    "LANGUAGE",
    "RUMBLE ON/OFF",
    "WIDESCREEN OFF/ON",
    "MUSIC",
    "SOUND",
    "OFF",
    "FULL",
    "BACK",
    "MENU",
    "SHUFFLE",
    "PAUSED",
    "NO MORE TILES",
    "FINISHED",
    "RESTART",
    "NEW GAME",
    "SCORE",
    "WINNER",
    "PLAYER 1",
    "PLAYER 2",
    "DRAW",
    "RANDOM LAYOUT",
    "DEFAULT",
    "SIMPLE",
    "OLD",
    "SPOOKY",
    "EGYPTIAN",
    "SPACE",
    "DEFAULT",
    "CROSS",
    "BUTTERFLY",
    "FORTRESS",
    "CRAB",
    "SPIDER",
    "FOUR BRIDGES",
    "CLOUD",
    "ARENA",
    "TIC TAC TOE",
    "TALE",
    "TIKAL"
};

const char* const german_lng[] = {
    "SPIELEN",
    "HI-SCORES",
    "SPIEL OPTIONEN",
    "TON OPTIONEN",
    "BEENDEN",
    "1 SPIELER",
    "SPIEL",
    "2 SPIELER",
    "CO-OP",
    "2 SPIELER",
    "VERSUS",
    "WEITER",
    "STEINE ÄNDERN",
    "LAYOUT ÄNDERN",
    "TIPPS AN/AUS",
    "SPRACHE",
    "VIBRIEREN AN/AUS",
    "BREITBILD AUS/AN",
    "MUSIK",
    "TON",
    "AUS",
    "VOLL",
    "ZURÜCK",
    "MENU",
    "MISCHEN",
    "PAUSE",
    "KEINE KOMBINATIONEN MEHR",
    "FERTIG",
    "NEUSTART",
    "NEUES SPIEL",
    "PUNKTZAHL",
    "GEWINNER",
    "SPIELER 1",
    "SPIELER 2",
    "UNENTSCHIEDEN",
    "ZUFÄLLIGES LAYOUT",
    "STANDARD",
    "EINFACH",
    "ALT",
    "GRUSELIG",
    "ÄGYPTISCH",
    "RAUM",
    "STANDARD",
    "KREUZ",
    "SCHMETTERLING",
    "FESTUNG",
    "KRABBE",
    "SPINNE",
    "VIER BRUECKEN",
    "WOLKE",
    "ARENA",
    "TIC TAC TOE",
    "TAL",
    "TIKAL"
};
