#include "languages.h"

const char english_lng[] = "PLAY GAME,HI-SCORES,GAME OPTIONS,SOUND OPTIONS,EXIT\n"
    "1 PLAYER\nGAME,2 PLAYER\nCO-OP,2 PLAYER\nVERSUS,CONTINUE\n"
    "CHANGE TILESET,CHANGE LAYOUT,HOVER HINT ON/OFF,LANGUAGE,RUMBLE ON/OFF,WIDESCREEN OFF/ON\n"
    "MUSIC,SOUND,OFF,FULL\n"
    "BACK,MENU,SHUFFLE,PAUSED,NO MORE TILES,FINISHED,RESTART,NEW GAME,"
    "SCORE,WINNER,PLAYER 1,PLAYER 2,DRAW,RANDOM LAYOUT,"
    "DEFAULT,CROSS,BUTTERFLY,FORTRESS,CRAB,SPIDER,FOUR BRIDGES,CLOUD,ARENA,TIC TAC TOE,TALE,TIKAL,"
    "DEFAULT,SIMPLE,OLD,SPOOKY,EGYPTIAN,SPACE";

const char german_lng[] = "SPIELEN,HI-SCORES,SPIELOPTIONEN,TONOPTIONEN,BEENDEN," //5
    "1 SPIELER,SPIEL,2 SPIELER,CO-OP,2 SPIELER,VERSUS,WEITER," //12
    "STEINE ÄNDERN,LAYOUT ÄNDERN,TIPPS AN/AUS,SPRACHE,VIBRIEREN AN/AUS,BREITBILD AUS/AN," //19
    "MUSIK,TON,AUS,VOLL\n" //23
    "ZURÜCK,MENU,MISCHEN,PAUSE,KEINE KOMBINATIONEN MEHR,FERTIG,NEUSTART,NEUES SPIEL," //31
    "PUNKTZAHL,GEWINNER,SPIELER 1,SPIELER 2,UNENTSCHIEDEN,ZUFÄLLIGES LAYOUT," //37
    "STANDARD,KREUZ,SCHMETTERLING,FESTUNG,KRABBE,SPINNE,VIER BRUECKEN,WOLKE,ARENA,TIC TAC TOE,TAL,TIKAL," //49
    "STANDARD,EINFACH,ALT,GRUSELIG,ÄGYPTISCH,RAUM";  //55
