#ifndef _languages_h_
#define _languages_h_

enum languages
{
    LNG_MMENU_PLAY = 0,
    LNG_MMENU_HISCORES,
    LNG_MMENU_GAMEOPTIONS,
    LNG_MMENU_SOUNDOPTIONS,
    LNG_MMENU_EXIT,
    LNG_PMENU_1PLAYER,
    LNG_PMENU_1PLAYERADD,
    LNG_PMENU_2PCOOP,
    LNG_PMENU_2PLAYERCOOP,
    LNG_PMENU_2PVERSUS,
    LNG_PMENU_VERSUS,
    LNG_PMENU_CONTINUE,
    LNG_OMENU_CTILESET,
    LNG_OMENU_CLAYOUT,
    LNG_OMENU_HOVERONOFF,
    LNG_OMENU_LANGUAGE,
    LNG_OMENU_RUMBLEONOFF,
    LNG_OMENU_WIDESCREENONOFF,
    LNG_SMENU_MUSIC,
    LNG_SMENU_SOUND,
    LNG_SMENU_OFF,
    LNG_SMENU_FULL,
    LNG_GAME_BACK,
    LNG_GAME_MENU,
    LNG_GAME_SHUFFLE,
    LNG_GAME_PAUSED,
    LNG_GAME_NOMORETILES,
    LNG_GAME_FINISHED,
    LNG_GAME_RESTART,
    LNG_GAME_NEW,
    LNG_GAME_SCORE,
    LNG_GAME_WINNER,
    LNG_GAME_PLAYER1,
    LNG_GAME_PLAYER2,
    LNG_GAME_DRAW,
    LNG_GAME_RANDOMLAYOUT,
    LNG_GAME_NEWHIGHSCORE,
    LNG_TILESET_DEFAULT,
    LNG_TILESET_SIMPLE,
    LNG_TILESET_OLD,
    LNG_TILESET_SPOOKY,
    LNG_TILESET_EGYPTIAN,
    LNG_TILESET_SPACE,
    LNG_LAYOUT_DEFAULT,
    LNG_LAYOUT_CROSS,
    LNG_LAYOUT_BUTTERFLY,
    LNG_LAYOUT_FORTRESS,
    LNG_LAYOUT_CRAB,
    LNG_LAYOUT_SPIDER,
    LNG_LAYOUT_FOUR_BRIDGES,
    LNG_LAYOUT_CLOUD,
    LNG_LAYOUT_ARENA,
    LNG_LAYOUT_TICTATOE,
    LNG_LAYOUT_TALE,
    LNG_LAYOUT_TIKAL,
    LNG_MAXENTRIES
};

extern const char* const english_lng[];
extern const char* const german_lng[];

int lng_IndexFromString( const char* str);

#endif
